name: CodeReviwer Docker Image

on:
  push:
    # Trigger when code is pushed to the main branch
    branches:
      - main  
  pull_request:
    # Trigger when a PR is created against the main branch
    branches:
      - main  
jobs:
  build:
    #specifies which OS to run
    runs-on: ubuntu-latest
    #loads the code in the selected repository    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    #sets up the docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #Cache file to say docker layers
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    #run to actually byild the project
    - name: Build Docker image
      run: |
        docker build -t codereviewer .
        docker tag codereviewer prabhusoham/codereviewer:latest
    #log into the dockerhub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #pushes the current image to the dockerhub
    - name: Push Docker image to DockerHub
      run: |
        docker push prabhusoham/codereviewer:latest
